---
- name: Restart Service on Legacy Windows 2008
  hosts: all
  gather_facts: false
  become: false
  tasks:
    - name: Stop the service (force Yes for dependencies)
      ansible.builtin.raw: cmd.exe /c "net stop Spooler /y"
      ignore_errors: true 

    - name: Start the service
      ansible.builtin.raw: cmd.exe /c "net start Spooler"
